audio:
  sample_rate: ${sample_rate}
defaults:
  - preprocess_dataset: parallel_audiobook_dataset


train_tar_sink:
  _target_: webdataset.ShardWriter
  pattern: "preprocessed_data/glob-train-%06d.tar.gz"
val_tar_sink:
  _target_: webdataset.ShardWriter
  pattern: "preprocessed_data/glob-val-%06d.tar.gz"
val_size: 3000
speaker_dict_path: "preprocessed_data/speakers.json"


